repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.11
    hooks:
      - id: terraform-fmt
      - id: tflint
